### ISSUE TITLE
The first test is always failing

### ISSUE THREAD

**Issue by ldgarber** [learn-co-curriculum/react-prop-types-lab#12]
I have completed this lab and all the checks are correct (validated against the solution code), but whatever test is the first to run in the test suite always fails. I have changed around the order of the tests, and then the test that used to fail passes, and whichever test is now first fails. 

I have no idea what could be causing this, but it's incredibly frustrating. 

The error I'm getting now (for the 'producer' test which I re-ordered to be the first one) is: 
  1) <Product /> `producer` prop should be optional:
     Error: This prop should be optional.
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toNotExist (node_modules/expect/lib/Expectation.js:59:28)
      at Context.<anonymous> (test/index-test.js:52:26)

**Comment by ipc103** [comment]
closed by #13
