### ISSUE TITLE
test may be broken.

### ISSUE THREAD

**Issue by rocketNeck** [learn-co-curriculum/react-prop-types-lab#14]
copy and pasted solution into "./components/Product.js" to validate issue.

always show at least one failing test. All other tests pass.

when I comment out the test for "prop name should be required" the failing test just moves to the next test.

**Comment by ipc103** [comment]
Thanks for raising this issue, @rocketNeck. I believe this issue has been fixed. Try running `npm install --save-dev react-test-renderer` if you continue to have issues. Going to close this for now.
